version: 2.1
orbs:
  node: circleci/node@5.0.2
  python: circleci/python@2.0.3
jobs:
  deploy_prod:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Deploy
          command: ssh -oStrictHostKeyChecking=no root@164.92.122.186 'cd /var/www/sadhan && git checkout . && git pull origin master && pip3 install -r ./requirements.txt && cd frontend && flutter upgrade && flutter build web && cd ../ systemctl restart systemd_web_server.service'
workflows:
  deploy_app:
    jobs:
      - deploy_prod:
          filters:
            branches:
              only: master
